Added PathFollowing Functionality add odometry
SaintsRobotics/frc2020 pull request #58
Opened 2020-02-19 17:48 UTC by noam987

2020-02-19 17:54 UTC, noam987 commented
Note the pids have not been tuned. That will be done ASAP

2020-02-19 22:21 UTC, delaynieym commented
For all of the nav Commands, stick them in a folder called nav.  Put that folder in either the subsystems folder or the commands folder

2020-02-20 01:49 UTC, dotnetprofessional requested changes

2020-02-20 01:49 UTC, dotnetprofessional commented on code/src/main/java/frc/robot/commands/OdometryCommand.java
> +        }
I don't understand why this needs to be outside the subsystem. I understand that you need something to keep polling the subsystem for position, however all the calculations seem like they can be done just as well in the subsystem with check for current x,y or simply a amIThereYet method. I'm most concerned that this is going to be hard to mock.

Is one of the reasons due to the amount of code needed in the subsystem? I maybe missing something.

2020-02-20 01:49 UTC, dotnetprofessional commented on code/src/main/java/frc/robot/commands/MoveToLocationCommand.java
> +    public MoveToLocationCommand(ILogger logger, IDrivetrainSubsystem subsystem, RobotConfig config, Pose2d position) {
the literals are not going to work well with an IoC. The pattern would be to have these added as properties. Then what ever wanted this class would set the properties at the point of scheduling.

2020-02-20 01:49 UTC, dotnetprofessional commented on code/src/main/java/frc/robot/RobotConfig.java
> +        public final SwerveDriveKinematics kinematics = new SwerveDriveKinematics(new Translation2d(swerveX, swerveY), new Translation2d(swerveX, -swerveY),
any reason for not just having this code in the SwerveDrivetrain class? It doesn't seem to be used anywhere else and this isn't  a constant in terms of a simple value.

2020-02-20 01:49 UTC, dotnetprofessional commented on code/src/main/java/frc/robot/commands/VisionAdjustCommand.java
> +        NetworkTableEntry ta = m_table.getEntry("ta");
the calls to NetworkTables would be better behind a class ie LimelightSensor or something. This makes it easier to mock this out. It also means the data can be used in more than one place.

Actually making it a subsystem will make it easier to keep polling the values.

2020-02-20 01:49 UTC, dotnetprofessional commented on code/src/main/java/frc/robot/commands/turnToHeading.java
> +public class turnToHeading extends TraceableCommand {
nit: Class names should start with a captial

2020-02-20 01:49 UTC, dotnetprofessional commented on code/src/main/java/frc/robot/commands/turnToHeading.java
> +        path[0] = new Pose2d(m_subsystem.getCurrentPosition().getTranslation(), new Rotation2d(heading));
I think Location would be a better choice as its tracking x,y

2020-02-20 01:49 UTC, dotnetprofessional commented on code/src/test/java/frc/robot/unit/subsystems/drivetrain/Feature_move_robot_using_high_level_commands.java
> +        // _drivetrain.rotate(rotation);
so can I assume all the tests are broken??

2022-03-05 01:10 UTC, closed without merging